apiVersion: v1
kind: Service
metadata:
  name: dnphoto
  labels:
    app: generator-photo
spec:
  ports:
    - port: 3000
  selector:
    app: generator-photo
    tier: dnphoto
  # clusterIP: None
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnphoto
  labels:
    app: generator-photo
spec:
  selector:
    matchLabels:
      app: generator-photo
      tier: dnphoto
  strategy:
    type: Recreate
  replicas: 5
  template:
    metadata:
      labels:
        app: generator-photo
        tier: dnphoto
    spec:
      containers:
        - image: jhitescia/api-nest-kube:latest
          imagePullPolicy: Always
          name: dnphoto
          ports:
            - containerPort: 3000
              name: generator-photo
