apiVersion: v1
kind: Service
metadata:
  name: frontDeploy
  labels:
    app: generatorPhoto
spec:
  ports:
    - port: 5000
  selector:
    app: generatorPhoto 
    tier: frontDeploy
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontDeploy 
  labels:
    app: generatorPhoto
spec:
  selector:
    matchLabels:
      app: generatorPhoto
      tier: frontDeploy
  strategy:
    type: Recreate
  replicas: 3
  template:
    metadata:
      labels:
        app: generatorPhoto
        tier: frontDeploy
    spec:
      containers:
      - image: tecpi/monster_icon:0.1
        name: frontDeploy
        env:
        - name: CONTEXT
          value: DEV
        ports:
        - containerPort: 5000
          name: frontDeploy
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3


