apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress 
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /deployement
          pathType: Prefix
          backend:
            service:
              name: generator-photo
              port:
                number: 5000